// -*- coding: utf-8 -*-

// Copyright (C) 2018 Nippon Telegraph and Telephone Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package opennsl

/*
#include <opennsl/types.h>
#include <opennsl/port.h>
*/
import "C"

//
// PortAbility
//
type PortAbility C.opennsl_port_ability_t

func (v *PortAbility) C() *C.opennsl_port_ability_t {
	return (*C.opennsl_port_ability_t)(v)
}

func NewPortAbility() *PortAbility {
	abil := &PortAbility{}
	abil.Init()
	return abil
}

func (v *PortAbility) Init() {
	C.opennsl_port_ability_t_init(v.C())
}

//
// PortAbilityMode
//
type PortAbilityMode C.int

func (v PortAbilityMode) C() C.int {
	return C.int(v)
}

const (
	PORT_ABILITY_10MB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_10MB
	PORT_ABILITY_100MB            PortAbilityMode = C.OPENNSL_PORT_ABILITY_100MB
	PORT_ABILITY_1000MB           PortAbilityMode = C.OPENNSL_PORT_ABILITY_1000MB
	PORT_ABILITY_2500MB           PortAbilityMode = C.OPENNSL_PORT_ABILITY_2500MB
	PORT_ABILITY_3000MB           PortAbilityMode = C.OPENNSL_PORT_ABILITY_3000MB
	PORT_ABILITY_5000MB           PortAbilityMode = C.OPENNSL_PORT_ABILITY_5000MB
	PORT_ABILITY_6000MB           PortAbilityMode = C.OPENNSL_PORT_ABILITY_6000MB
	PORT_ABILITY_10GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_10GB
	PORT_ABILITY_11GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_11GB
	PORT_ABILITY_12GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_12GB
	PORT_ABILITY_12P5GB           PortAbilityMode = C.OPENNSL_PORT_ABILITY_12P5GB
	PORT_ABILITY_13GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_13GB
	PORT_ABILITY_15GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_15GB
	PORT_ABILITY_16GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_16GB
	PORT_ABILITY_20GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_20GB
	PORT_ABILITY_21GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_21GB
	PORT_ABILITY_23GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_23GB
	PORT_ABILITY_24GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_24GB
	PORT_ABILITY_25GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_25GB
	PORT_ABILITY_27GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_27GB
	PORT_ABILITY_30GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_30GB
	PORT_ABILITY_32GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_32GB
	PORT_ABILITY_40GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_40GB
	PORT_ABILITY_42GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_42GB
	PORT_ABILITY_48GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_48GB
	PORT_ABILITY_50GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_50GB
	PORT_ABILITY_53GB             PortAbilityMode = C.OPENNSL_PORT_ABILITY_53GB
	PORT_ABILITY_100GB            PortAbilityMode = C.OPENNSL_PORT_ABILITY_100GB
	PORT_ABILITY_106GB            PortAbilityMode = C.OPENNSL_PORT_ABILITY_106GB
	PORT_ABILITY_120GB            PortAbilityMode = C.OPENNSL_PORT_ABILITY_120GB
	PORT_ABILITY_127GB            PortAbilityMode = C.OPENNSL_PORT_ABILITY_127GB
	PORT_ABILITY_INTERFACE_TBI    PortAbilityMode = C.OPENNSL_PORT_ABILITY_INTERFACE_TBI
	PORT_ABILITY_INTERFACE_MII    PortAbilityMode = C.OPENNSL_PORT_ABILITY_INTERFACE_MII
	PORT_ABILITY_INTERFACE_GMII   PortAbilityMode = C.OPENNSL_PORT_ABILITY_INTERFACE_GMII
	PORT_ABILITY_INTERFACE_SGMII  PortAbilityMode = C.OPENNSL_PORT_ABILITY_INTERFACE_SGMII
	PORT_ABILITY_INTERFACE_XGMII  PortAbilityMode = C.OPENNSL_PORT_ABILITY_INTERFACE_XGMII
	PORT_ABILITY_INTERFACE_QSGMII PortAbilityMode = C.OPENNSL_PORT_ABILITY_INTERFACE_QSGMII
	PORT_ABILITY_INTERFACE_CGMII  PortAbilityMode = C.OPENNSL_PORT_ABILITY_INTERFACE_CGMII
	PORT_ABILITY_MEDIUM_COPPER    PortAbilityMode = C.OPENNSL_PORT_ABILITY_MEDIUM_COPPER
	PORT_ABILITY_MEDIUM_FIBER     PortAbilityMode = C.OPENNSL_PORT_ABILITY_MEDIUM_FIBER
	PORT_ABILITY_MEDIUM_BACKPLANE PortAbilityMode = C.OPENNSL_PORT_ABILITY_MEDIUM_BACKPLANE
	PORT_ABILITY_LB_NONE          PortAbilityMode = C.OPENNSL_PORT_ABILITY_LB_NONE
	PORT_ABILITY_LB_MAC           PortAbilityMode = C.OPENNSL_PORT_ABILITY_LB_MAC
	PORT_ABILITY_LB_PHY           PortAbilityMode = C.OPENNSL_PORT_ABILITY_LB_PHY
	PORT_ABILITY_LB_LINE          PortAbilityMode = C.OPENNSL_PORT_ABILITY_LB_LINE
	PORT_ABILITY_AUTONEG          PortAbilityMode = C.OPENNSL_PORT_ABILITY_AUTONEG
	PORT_ABILITY_COMBO            PortAbilityMode = C.OPENNSL_PORT_ABILITY_COMBO
	PORT_ABILITY_PAUSE_TX         PortAbilityMode = C.OPENNSL_PORT_ABILITY_PAUSE_TX
	PORT_ABILITY_PAUSE_RX         PortAbilityMode = C.OPENNSL_PORT_ABILITY_PAUSE_RX
	PORT_ABILITY_PAUSE            PortAbilityMode = C.OPENNSL_PORT_ABILITY_PAUSE
	PORT_ABILITY_PAUSE_ASYMM      PortAbilityMode = C.OPENNSL_PORT_ABILITY_PAUSE_ASYMM
	PORT_ABILITY_FEC_NONE         PortAbilityMode = C.OPENNSL_PORT_ABILITY_FEC_NONE
	PORT_ABILITY_FEC_CL74         PortAbilityMode = C.OPENNSL_PORT_ABILITY_FEC_CL74
	PORT_ABILITY_FEC_CL91         PortAbilityMode = C.OPENNSL_PORT_ABILITY_FEC_CL91
	PORT_ABILITY_EEE_100MB_BASETX PortAbilityMode = C.OPENNSL_PORT_ABILITY_EEE_100MB_BASETX
	PORT_ABILITY_EEE_1GB_BASET    PortAbilityMode = C.OPENNSL_PORT_ABILITY_EEE_1GB_BASET
	PORT_ABILITY_EEE_10GB_BASET   PortAbilityMode = C.OPENNSL_PORT_ABILITY_EEE_10GB_BASET
	PORT_ABILITY_EEE_10GB_KX      PortAbilityMode = C.OPENNSL_PORT_ABILITY_EEE_10GB_KX
	PORT_ABILITY_EEE_10GB_KX4     PortAbilityMode = C.OPENNSL_PORT_ABILITY_EEE_10GB_KX4
	PORT_ABILITY_EEE_10GB_KR      PortAbilityMode = C.OPENNSL_PORT_ABILITY_EEE_10GB_KR
	PORT_ABILITY_CHANNEL_LONG     PortAbilityMode = C.OPENNSL_PORT_ABILITY_CHANNEL_LONG
	PORT_ABILITY_CHANNEL_SHORT    PortAbilityMode = C.OPENNSL_PORT_ABILITY_CHANNEL_SHORT
)

//
// PortAbil
//
type PortAbil C.opennsl_port_abil_t

func (v PortAbil) C() C.opennsl_port_abil_t {
	return C.opennsl_port_abil_t(v)
}

const (
	PORT_ABIL_10MB_HD     PortAbil = C.OPENNSL_PORT_ABIL_10MB_HD
	PORT_ABIL_10MB_FD     PortAbil = C.OPENNSL_PORT_ABIL_10MB_FD
	PORT_ABIL_100MB_HD    PortAbil = C.OPENNSL_PORT_ABIL_100MB_HD
	PORT_ABIL_100MB_FD    PortAbil = C.OPENNSL_PORT_ABIL_100MB_FD
	PORT_ABIL_1000MB_HD   PortAbil = C.OPENNSL_PORT_ABIL_1000MB_HD
	PORT_ABIL_1000MB_FD   PortAbil = C.OPENNSL_PORT_ABIL_1000MB_FD
	PORT_ABIL_2500MB_HD   PortAbil = C.OPENNSL_PORT_ABIL_2500MB_HD
	PORT_ABIL_2500MB_FD   PortAbil = C.OPENNSL_PORT_ABIL_2500MB_FD
	PORT_ABIL_3000MB_HD   PortAbil = C.OPENNSL_PORT_ABIL_3000MB_HD
	PORT_ABIL_3000MB_FD   PortAbil = C.OPENNSL_PORT_ABIL_3000MB_FD
	PORT_ABIL_10GB_HD     PortAbil = C.OPENNSL_PORT_ABIL_10GB_HD
	PORT_ABIL_10GB_FD     PortAbil = C.OPENNSL_PORT_ABIL_10GB_FD
	PORT_ABIL_12GB_HD     PortAbil = C.OPENNSL_PORT_ABIL_12GB_HD
	PORT_ABIL_12GB_FD     PortAbil = C.OPENNSL_PORT_ABIL_12GB_FD
	PORT_ABIL_13GB_HD     PortAbil = C.OPENNSL_PORT_ABIL_13GB_HD
	PORT_ABIL_13GB_FD     PortAbil = C.OPENNSL_PORT_ABIL_13GB_FD
	PORT_ABIL_16GB_HD     PortAbil = C.OPENNSL_PORT_ABIL_16GB_HD
	PORT_ABIL_16GB_FD     PortAbil = C.OPENNSL_PORT_ABIL_16GB_FD
	PORT_ABIL_TBI         PortAbil = C.OPENNSL_PORT_ABIL_TBI
	PORT_ABIL_MII         PortAbil = C.OPENNSL_PORT_ABIL_MII
	PORT_ABIL_GMII        PortAbil = C.OPENNSL_PORT_ABIL_GMII
	PORT_ABIL_SGMII       PortAbil = C.OPENNSL_PORT_ABIL_SGMII
	PORT_ABIL_XGMII       PortAbil = C.OPENNSL_PORT_ABIL_XGMII
	PORT_ABIL_LB_MAC      PortAbil = C.OPENNSL_PORT_ABIL_LB_MAC
	PORT_ABIL_LB_PHY      PortAbil = C.OPENNSL_PORT_ABIL_LB_PHY
	PORT_ABIL_LB_NONE     PortAbil = C.OPENNSL_PORT_ABIL_LB_NONE
	PORT_ABIL_AN          PortAbil = C.OPENNSL_PORT_ABIL_AN
	PORT_ABIL_COMBO       PortAbil = 0x80000000 // C.OPENNSL_PORT_ABIL_COMBO
	PORT_ABIL_PAUSE_TX    PortAbil = C.OPENNSL_PORT_ABIL_PAUSE_TX
	PORT_ABIL_PAUSE_RX    PortAbil = C.OPENNSL_PORT_ABIL_PAUSE_RX
	PORT_ABIL_PAUSE       PortAbil = C.OPENNSL_PORT_ABIL_PAUSE
	PORT_ABIL_10B         PortAbil = C.OPENNSL_PORT_ABIL_10B
	PORT_ABIL_PAUSE_ASYMM PortAbil = C.OPENNSL_PORT_ABIL_PAUSE_ASYMM
	PORT_ABIL_10MB        PortAbil = C.OPENNSL_PORT_ABIL_10MB
	PORT_ABIL_100MB       PortAbil = C.OPENNSL_PORT_ABIL_100MB
	PORT_ABIL_1000MB      PortAbil = C.OPENNSL_PORT_ABIL_1000MB
	PORT_ABIL_2500MB      PortAbil = C.OPENNSL_PORT_ABIL_2500MB
	PORT_ABIL_3000MB      PortAbil = C.OPENNSL_PORT_ABIL_3000MB
	PORT_ABIL_10GB        PortAbil = C.OPENNSL_PORT_ABIL_10GB
	PORT_ABIL_12GB        PortAbil = C.OPENNSL_PORT_ABIL_12GB
	PORT_ABIL_13GB        PortAbil = C.OPENNSL_PORT_ABIL_13GB
	PORT_ABIL_16GB        PortAbil = C.OPENNSL_PORT_ABIL_16GB
	PORT_ABIL_HD          PortAbil = C.OPENNSL_PORT_ABIL_HD
	PORT_ABIL_FD          PortAbil = C.OPENNSL_PORT_ABIL_FD
	PORT_ABIL_SPD_ANY     PortAbil = C.OPENNSL_PORT_ABIL_SPD_ANY
)
